DROP TABLE IF EXISTS users, user_friend, rating_MPA, genre, films, user_film_like, film_genre;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    birthday DATE
);

CREATE TABLE IF NOT EXISTS user_friend (
    user_id BIGINT NOT NULL REFERENCES users(id),
    friend_id BIGINT NOT NULL REFERENCES users(id),
    UNIQUE (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS rating_MPA (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS genre (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    description VARCHAR(500),
    release_date DATE,
    duration INTEGER CHECK (duration > 0),
    rating_id BIGINT REFERENCES rating_MPA(id)
);

CREATE TABLE IF NOT EXISTS user_film_like (
    user_id BIGINT REFERENCES users(id),
    film_id BIGINT REFERENCES films(id),
    UNIQUE (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id BIGINT REFERENCES films(id),
    genre_id BIGINT REFERENCES genre(id),
    UNIQUE (film_id, genre_id)
);